name: Artifact

on: [push]

env:
  ARTIFACT_NAME: myartifact

jobs:
  main:
   run-on: ubuntu-latest
   steps: 
   - name: checkout the code
     use: actions/checkoutt@v2
   - name: Upload the artifact
     use: actions/upload-artfactt@v2
     with:
       name: ${{ env.ARTIFACT_NAME }}
       path: .
